clean up bash deploy script

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -62,25 +62,12 @@ declare -r SYNTAX=$(cat <<EOF
 
       Actions:
         --sync=<directory>: Synchronize files between project and S3
+        --upload-res*: Upload newest resume
+        --upload-letter: Upload newest cover letter  
         --list: List all the content
+        --size: show sizes
         --delete-all: Delete all content
         --remove: Remove site bucket
-
-        Un-refactored  
-        --upload: Upload all pertinent files and directories
-        --updoad-file=<file>: TODO
-        --upload-dir=<directory>: Upload a given directory
-        --upload-res*: Upload newest resume
-        --delete-file=<file>: TODO
-        --delete-dir=<directory>: Delete a directory
-        
-        --delete-logs: Delete all logs
-        --remove-log: Remove the log bucket
-        
-        --size: show sizes
-
-      Flags:
-        --pwd: use current directory for uploads
 
 
 EOF
@@ -89,24 +76,14 @@ EOF
 declare -r SCRIPT_DIR="$( dirname ${0} )"
 declare -r CONF_FILE="${SCRIPT_DIR}/deploy.conf.sh"
 
-# actions (refactored)
+# actions 
 declare -i SYNC=${FALSE}
 declare -i LIST=${FALSE}
 declare -i DELETE_ALL=${FALSE}
 declare -i OPEN=${FALSE} 
-
-
-declare -i UPLOAD=${FALSE}
-declare -i UPLOAD_DIR=${FALSE}
-declare -i UPLOAD_FILE=${FALSE}
+declare -i REMOVE=${FALSE} 
 declare -i UPLOAD_RESUME=${FALSE}
 declare -i UPLOAD_LETTER=${FALSE}
-declare -i DELETE=${FALSE}
-
-declare -i DELETE_DIR=${FALSE}
-declare -i DELETE_LOGS=${FALSE}
-declare -i REMOVE_LOG=${FALSE}
-
 declare -i SIZE=${FALSE}
 
 # flags
@@ -171,13 +148,18 @@ show_help() {
 source "${CONF_FILE}" \
   || die "Unable to open configuration file: ${CONF_FILE}" 1
 
-# 
-# Refactor 
-#
-# BEGIN WORKING ROUTINES
-# * primary working routines for angular v6 deployment
 __sync() {
   aws s3 --profile "${AWS_PROFILE}" sync "${SOURCE_DIR}" s3://${SITE_BUCKET}
+}
+
+__upload_resume() {
+  [[ -f "${RESUME_PATH}" ]] || die "Resume was not found: ${RESUME_PATH}." 4
+  aws s3 --profile "${AWS_PROFILE}" cp "${RESUME_PATH}" s3://${SITE_BUCKET}/assets/documents/${RESUME_FILE}
+}
+
+__upload_letter() {
+  [[ -f "${LETTER_PATH}" ]] || die "Cover letter was not found: ${LETTER_PATH}." 5
+  aws s3 --profile "${AWS_PROFILE}" cp "${LETTER_PATH}" s3://${SITE_BUCKET}/documents/${LETTER_FILE}
 }
 
 __list() {
@@ -197,73 +179,17 @@ __open() {
   open "${SITE_ENDPOINT}"
 }
 
-# END WORKING ROUTINES
-#
-#  Below are reference routines, will be moved up as they are refactored
-#
-__upload() {
-  for file in "${FILES[@]}"; do
-    printf "Copying file: %s\n" "${file}"
-    aws s3 --profile "${AWS_PROFILE}" cp ${SITE_DIR}/${file} s3://${SITE_BUCKET}
-  done
-
-  for dir in "${DIRS[@]}"; do
-    printf "Copying directory: %s\n" "${dir}"
-    aws s3 --profile "${AWS_PROFILE}" cp ${SITE_DIR}/${dir}/ s3://${SITE_BUCKET}/${dir} \
-      --recursive \
-      --exclude '*DS_Store*'
-  done
-}
-
-
-__upload_dir() {
-  [[ -z "${DIRECTORY}" ]] && die "Directory argument is required" 2
-
-  aws s3 x --profile "${AWS_PROFILE}" cp "${SITE_DIR}/${DIRECTORY}/" s3://${SITE_BUCKET}/${DIRECTORY} \
-    --recursive \
-    --exclude '*DS_Store*'
-}
-
-__upload_file() {
-  [[ -f "${DIRECTORY}" ]] && die "Directory argument is required" 2
-
-  aws s3 --profile "${AWS_PROFILE}" cp "${SITE_DIR}/${FILE}" s3://${SITE_BUCKET}/${FILE}
-}
-
-__delete_dir() {
-  aws s3 --profile "${AWS_PROFILE}" rm s3://${DIRECTORY}/ --recursive
-}
-
-__delete_logs() {
-  aws s3 --profile "${AWS_PROFILE}" rm s3://${LOG_BUCKET}/ --recursive
-}
-
-__remove_log() {
-  #__delete_logs
-  aws s3 --profile "${AWS_PROFILE}" rb s3://${LOG_BUCKET} --force
-}
-
-
-__size() {
-  aws s3api list-objects \
-    --bucket ${SITE_BUCKET} \
-    --output text \
-    --query "[sum(Contents[].Size), length(Contents[])]"
-}
-
 __check_aws() {
   which aws &>/dev/null || die "AWS was not available, run virtualenv?" 2
 }
 
-__upload_resume() {
-  [[ -f "${RESUME_PATH}" ]] || die "Resume was not found: ${RESUME_PATH}." 4
-  aws s3 --profile "${AWS_PROFILE}" cp "${RESUME_PATH}" s3://${SITE_BUCKET}/documents/${RESUME_FILE}
+__size() {
+  aws s3api list-objects \
+    --bucket ${SITE_BUCKET} \
+    --output json \
+    --query "[sum(Contents[].Size), length(Contents[])]"
 }
 
-__upload_letter() {
-  [[ -f "${LETTER_PATH}" ]] || die "Cover letter was not found: ${LETTER_PATH}." 5
-  aws s3 --profile "${AWS_PROFILE}" cp "${LETTER_PATH}" s3://${SITE_BUCKET}/documents/${LETTER_FILE}
-}
 
 __open_resume() {
   local dt=$( date +'%Y%m%d')
@@ -279,47 +205,16 @@ __get_opts() {
     local arg="${1}"; shift;
     case ${arg} in
       # BEGIN WORKING
-      --help)    show_help                   ;;
-      --version) show_version                ;;
-      --sync*)            SYNC=${TRUE}
-        [[ ${arg} =~ '=' ]] && DIRECTORY="${arg#*=}"
-        ;;
-      --list)            LIST=${TRUE}        ;;  
-      --open)            OPEN=${TRUE}        ;;
-      --delete-all)      DELETE_ALL=${TRUE}  ;;
-      --remove)          REMOVE=${TRUE}      ;;
-      # END WORKING
-
-      --upload)          UPLOAD=${TRUE}      ;;
-      --upload-file*)
-        UPLOAD_FILE=${TRUE}
-        [[ ${arg} =~ '=' ]] && FILE="${arg#*=}"
-        ;;
+      --help)    show_help                     ;;
+      --version) show_version                  ;;
+      --sync*)            SYNC=${TRUE}         ;;
+      --remove)          REMOVE=${TRUE}        ;;
       --upload-res*)     UPLOAD_RESUME=${TRUE} ;;
-      --upload-letter)   UPLOAD_LETTER=${TRUE} ;;
-      --open-res*)
-        __open_resume; exit 0; ;;
-      --delete)          DELETE=${TRUE}      ;;
-     
-      --delete-dir*)
-        DELETE_DIR=${TRUE}
-        [[ ${arg} =~ '=' ]] && DIRECTORY="${arg#*=}"
-        ;;
-      --delete-log*)     DELETE_LOGS=${TRUE} ;;
-      --remove-log)      REMOVE_LOG=${TRUE}  ;;
-      --dry-run)         DRY_RUN=${TRUE}     ;;
-    
-      --size)            SIZE=${TRUE}        ;;
-      --upload-dir*)
-        UPLOAD_DIR=${TRUE}
-        [[ ${arg} =~ '=' ]] && DIRECTORY="${arg#*=}"
-        ;;
-      # Flags
-      --pwd)
-        USE_PWD=${TRUE}
-        SITE_DIR='.'
-        ;;
-
+      --upload-letter)   UPLOAD_LETTER=${TRUE} ;;  
+      --list)            LIST=${TRUE}          ;;  
+      --delete-all)      DELETE_ALL=${TRUE}    ;;
+      --size)            SIZE=${TRUE}          ;;
+      --open)            OPEN=${TRUE}          ;;
       *) die "Unknown option: ${arg}" ;;
    esac
   done
@@ -333,20 +228,20 @@ __dispatch() {
   (( LIST )) && __list
   (( OPEN )) && __open
   (( SYNC )) && __sync
+  (( UPLOAD_RESUME )) && __upload_resume
+  (( UPLOAD_LETTER )) && __upload_letter
   (( DELETE_ALL )) && __delete_all
   (( REMOVE )) && __remove
 
-  (( UPLOAD )) && __upload
-  (( UPLOAD_DIR )) && __upload_dir
-  (( UPLOAD_FILE )) && __upload_file
-  (( UPLOAD_RESUME )) && __upload_resume
-  (( UPLOAD_LETTER )) && __upload_letter
-  (( DELETE )) && __delete
+  # (( UPLOAD )) && __upload
+  # (( UPLOAD_DIR )) && __upload_dir
+  # (( UPLOAD_FILE )) && __upload_file
+  # (( DELETE )) && __delete
   
-  (( DELETE_DIR )) && __delete_dir
-  (( DELETE_LOGS )) && __delete_logs
-  (( REMOVE_LOG )) && __remove_log
-  (( SIZE )) && __size
+  # (( DELETE_DIR )) && __delete_dir
+  # (( DELETE_LOGS )) && __delete_logs
+  # (( REMOVE_LOG )) && __remove_log
+  # (( SIZE )) && __size
   return 0
 }
 
